### ISSUE TITLE
Question about training warm-up lexical model with BM25 negatives.

### ISSUE THREAD

**Issue by jetou** [drogozhang/LED#3]
I saw in your python code "train_splade_retriever.py", 

target = torch.arange(ga_emb_query.shape[0], device=ga_emb_query.device, dtype=torch.long) * num_docs

I don't know for sure why you didn't pass the relevance label of passage-query pair explicitly.
It seems that you still utilize In-Batch-Negative sampling methods instead of BM25 negative as in your paper. So I want to make sure it is right or not, and how could I train this model with BM25 negatives.

**Comment by drogozhang** [comment]
Hi, thanks for your interest!

I may not fully understand your question. "In-batch-negative" is a technique for scaling up the negative examples for more effective training. In this method, within the same batch, the positive/negative passages for other queries are **ALSO** used as negatives for one query, **In addition to the negative examples sampled by BM25 or other sampling methods**. This trick can be employed during any training phase (warm-up and continuous training) and is commonly applied in the training of other dense retrievers.

Therefore, it can integrate with the BM25 or self-mining methods, which are ways of sampling negatives.

In short, yes, it is correct.
